spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user
    username: id
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect