spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user
    username: id
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

jwt:
  secret: fef68ee79a5e32ad0b5f82e5cdbb255b30d127a473258e3f5c0322c094052a684da0f34f8d28044d84c7e2ceb5593678df19689946adeab5acc5d3079dd26b0a
  access-token-expiration-hour: 2
  refresh-token-expiration-hour: 24

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security.web.FilterChainProxy: DEBUG
    org.springframework.security.authentication: DEBUG