version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: userauth_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: user
      POSTGRES_USER: id
      POSTGRES_PASSWORD: password
    volumes:
      - ./data:/var/lib/postgresql/data
