version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: userauth_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: user
      POSTGRES_USER: id
      POSTGRES_PASSWORD: password
    volumes:
      - ./data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"

  user-api:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: user-api
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/user
      SPRING_DATASOURCE_USERNAME: id
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"