### 회원 가입 API
POST http://localhost:8080/signup
Content-Type: application/json

{
  "email": "email@email.com",
  "password": "password123",
  "name": "Younghwan Choi"
}

### 로그인 API
POST http://localhost:8080/signin
Content-Type: application/json

{
  "email": "email@email.com",
  "password": "password123"
}