### 회원 가입 API
POST http://localhost:8080/signup
Content-Type: application/json

{
  "email": "email@email.com",
  "password": "password123",
  "name": "Younghwan Choi"
}

### 로그인 API
POST http://localhost:8080/signin
Content-Type: application/json

{
  "email": "email@email.com",
  "password": "password123"
}

### 사용자 정보 조회 API
GET http://localhost:8080/users/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwicm9sZXMiOlsiUk9MRV9NRU1CRVIiXSwiaWF0IjoxNzU0MjIyODgyLCJleHAiOjE3NTQyMzAwODJ9.C5BP9p8ds_5r5gD6_VZLxImSesubK9I77Fr5oTB0FGlz-K5A6mWP7uyfJHP238ngZg9wWg-_ncwg-Rs-En-MZA

### 사용자 정보 수정 API
PUT http://localhost:8080/users/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwicm9sZXMiOlsiUk9MRV9NRU1CRVIiXSwiaWF0IjoxNzU0MjIyODgyLCJleHAiOjE3NTQyMzAwODJ9.C5BP9p8ds_5r5gD6_VZLxImSesubK9I77Fr5oTB0FGlz-K5A6mWP7uyfJHP238ngZg9wWg-_ncwg-Rs-En-MZA
Content-Type: application/json

{
  "email": "email@email2.com",
  "name": "name2"
}
